/* WINDOW VARIABLES */
const GLint WINDOW_HEIGHT = 800;
const GLint WINDOW_WIDTH = 1280;
const GLint WINDOW_Z_NEAR = 1;
const GLint WINDOW_Z_FAR = 100000000;
const GLint WINDOW_FOV = 70;
GLdouble WINDOW_STARTING_X = 0.0f;
GLdouble WINDOW_STARTING_Y = 0.0f;
GLdouble WINDOW_STARTING_Z = -6500000.0f;

/* VARIABLES */
const GLdouble TOTAL_DEGREES = 360.0f;
const GLdouble AU = 149500000.0f;
GLint CURRENT_TIME = 1000.0f;
GLfloat SIMULATION_INCREASE = 1.0f;
GLfloat SIMULATION_SPEED = 10.0f;
GLfloat SIMULATION_LAST_INCREASE = 0.0f;
GLfloat SIMULATION_LAST_INCREASE_TIME = 0.0f;

Camera camera;

Solarsystem solarsystem;
